name= "pastebin"
compatibility_date = "2023-11-28"
account_id= "e2dd9771dd5ad7a0159c19759e815703"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.amcirccf.ggff.net", custom_domain = true }

kv_namespaces = [
  { binding = "kvv", id = "d21fc4725b6047c38a82806ff36e82a1" },
  { binding = "Imagine", id ="dbf2694cccb84591988a3ae7d5332032" }
]

[site]
bucket = "./static/dist"
